🔧 Improve developer scripts

diff --git a/scripts/pre-push b/scripts/pre-push
--- a/scripts/pre-push
+++ b/scripts/pre-push
@@ -1,25 +1,42 @@
 #!/bin/bash # Environment
 set -euo pipefail # Error handling and Strict mode
 
+set -euo pipefail # Error handling and Strict mode
+
+function checkIfError() {
+    if [ "$1" -ne 0 ] || [ "$2" -ne 0 ]; then
+        return 1
+    fi
+
+    return 0
+}
+
 echo "Running pre-commit checks..."
 
-source snyk.env
+export $(cat .env | grep SNYK) # Load Snyk token from .env file
 tokenFileResult=$? # Save the exit status of the previous command
 
 echo ""
 
 if [[ $tokenFileResult -ne 0 ]]; then
-    echo "RESULT: Pre-push checks failed. Please create the snyk.env file with the token."
+    echo "RESULT: Pre-push checks failed. Please create the .env file with the token."
     echo ""
     exit 1
 fi
 
+# Run static analysis tools
+npx snyk code test --all-projects
+checkIfError $? 0 # Accumulate way to check if the previous command was successful
+snykStatus=$? # Save the exit of the function
+
+# Run dependency checks
 npx snyk test --all-projects
-snykResult=$? # Save the exit status of the previous command
+checkIfError $snykStatus $? # Accumulate way to check if the previous command was successful
+snykStatus=$? # Save the exit of the function
 
 echo ""
 
-if [[ $snykResult -ne 0 ]]; then
+if [[ $snykStatus -ne 0 ]]; then
     echo "RESULT: Pre-push checks failed. Please fix the issues before committing."
     echo ""
     exit 1
